"""add_confluence_integration_support

Revision ID: 3939584b27df
Revises: a1b2c3d4e5f6
Create Date: 2026-04-29 10:25:19.719187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3939584b27df'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # CREATE the runbook_source_type ENUM first (before using it)
    op.execute("CREATE TYPE runbook_source_type AS ENUM ('file', 'confluence', 'github', 'google_docs')")

    op.alter_column('alert_groups', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('alert_groups', 'severity',
               existing_type=postgresql.ENUM('P1', 'P2', 'P3', name='severity_enum'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('alert_groups', 'triage_status',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('alert_groups', 'retry_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_alert_groups_active_lookup'), table_name='alert_groups', postgresql_where="((status)::text = 'active'::text)")
    op.drop_index(op.f('idx_alert_groups_created_at'), table_name='alert_groups')
    op.drop_index(op.f('idx_alert_groups_job_id'), table_name='alert_groups')
    op.drop_index(op.f('idx_alert_groups_thread_id'), table_name='alert_groups')
    op.drop_index(op.f('idx_alert_groups_triage_created'), table_name='alert_groups')
    op.drop_index(op.f('idx_alert_groups_triage_status'), table_name='alert_groups')
    op.create_index(op.f('ix_alert_groups_job_id'), 'alert_groups', ['job_id'], unique=False)
    op.create_index(op.f('ix_alert_groups_thread_id'), 'alert_groups', ['thread_id'], unique=False)
    op.drop_index(op.f('idx_alerts_group_id'), table_name='alerts', postgresql_where='(group_id IS NOT NULL)')
    op.drop_index(op.f('idx_alerts_ungrouped'), table_name='alerts', postgresql_where='(group_id IS NULL)')
    op.create_index(op.f('ix_alerts_group_id'), 'alerts', ['group_id'], unique=False)
    op.add_column('app_config', sa.Column('external_runbook_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('app_config', 'chaos_system_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('app_config', 'automatic_triage',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('app_config', 'alert_grouping_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_fault_ledger_id'), 'fault_ledger', ['id'], unique=False)
    op.add_column('runbooks', sa.Column('source_type', sa.Enum('file', 'confluence', 'github', 'google_docs', name='runbook_source_type'), server_default='file', nullable=False))
    op.add_column('runbooks', sa.Column('source_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=True))
    op.create_index('idx_runbooks_confluence_page_id_unique', 'runbooks', [sa.literal_column("((source_metadata->>'page_id'))")], unique=True, postgresql_where=sa.text("source_type = 'confluence' AND source_metadata->>'page_id' IS NOT NULL"))
    op.create_index('idx_runbooks_source_metadata_gin', 'runbooks', ['source_metadata'], unique=False, postgresql_using='gin')
    op.create_index('idx_runbooks_source_type', 'runbooks', ['source_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_runbooks_source_type', table_name='runbooks')
    op.drop_index('idx_runbooks_source_metadata_gin', table_name='runbooks', postgresql_using='gin')
    # DROP the runbook_source_type ENUM
    op.execute("DROP TYPE IF EXISTS runbook_source_type")

    op.drop_index('idx_runbooks_confluence_page_id_unique', table_name='runbooks', postgresql_where=sa.text("source_type = 'confluence' AND source_metadata->>'page_id' IS NOT NULL"))
    op.drop_column('runbooks', 'source_metadata')
    op.drop_column('runbooks', 'source_type')
    op.drop_index(op.f('ix_fault_ledger_id'), table_name='fault_ledger')
    op.alter_column('app_config', 'alert_grouping_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('app_config', 'automatic_triage',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('app_config', 'chaos_system_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.drop_column('app_config', 'external_runbook_config')
    op.drop_index(op.f('ix_alerts_group_id'), table_name='alerts')
    op.create_index(op.f('idx_alerts_ungrouped'), 'alerts', ['created_at'], unique=False, postgresql_where='(group_id IS NULL)')
    op.create_index(op.f('idx_alerts_group_id'), 'alerts', ['group_id'], unique=False, postgresql_where='(group_id IS NOT NULL)')
    op.drop_index(op.f('ix_alert_groups_thread_id'), table_name='alert_groups')
    op.drop_index(op.f('ix_alert_groups_job_id'), table_name='alert_groups')
    op.create_index(op.f('idx_alert_groups_triage_status'), 'alert_groups', ['triage_status'], unique=False)
    op.create_index(op.f('idx_alert_groups_triage_created'), 'alert_groups', ['triage_status', 'created_at'], unique=False)
    op.create_index(op.f('idx_alert_groups_thread_id'), 'alert_groups', ['thread_id'], unique=False)
    op.create_index(op.f('idx_alert_groups_job_id'), 'alert_groups', ['job_id'], unique=False)
    op.create_index(op.f('idx_alert_groups_created_at'), 'alert_groups', ['created_at'], unique=False)
    op.create_index(op.f('idx_alert_groups_active_lookup'), 'alert_groups', ['updated_at'], unique=False, postgresql_where="((status)::text = 'active'::text)")
    op.alter_column('alert_groups', 'retry_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('alert_groups', 'triage_status',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'pending'::character varying"),
               existing_nullable=False)
    op.alter_column('alert_groups', 'severity',
               existing_type=postgresql.ENUM('P1', 'P2', 'P3', name='severity_enum'),
               server_default=sa.text("'P3'::severity_enum"),
               existing_nullable=False)
    op.alter_column('alert_groups', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'active'::character varying"),
               existing_nullable=False)
    # ### end Alembic commands ###
