"""Add diagnostic_mcp_servers column to app_config

Revision ID: 4569c8b1cbd0
Revises: 7998f6833b63
Create Date: 2024-12-14 14:30:00.000000

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4569c8b1cbd0'
down_revision = '7998f6833b63'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_config',
                  sa.Column('diagnostic_mcp_servers', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_config', 'diagnostic_mcp_servers')
    # ### end Alembic commands ###
