"""Initial database

Revision ID: 5fc4b1ca348f
Revises: 
Create Date: 2025-09-24 05:08:30.629959

"""
from typing import Sequence, Union

import pgvector
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5fc4b1ca348f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('external_id', sa.String(), nullable=False),
                    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
                    sa.Column('alert_source', sa.String(), nullable=True),
                    sa.Column('alert_status', sa.String(), nullable=True),
                    sa.Column('severity', sa.Enum('P1', 'P2', 'P3', name='severity_enum'), nullable=True),
                    sa.Column('alert_name', sa.String(), nullable=True),
                    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'),
                              nullable=False),
                    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'),
                              nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_alerts_external_id'), 'alerts', ['external_id'], unique=False)
    op.create_table('app_config',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('enabled_severities', postgresql.ARRAY(sa.Enum('P1', 'P2', 'P3', name='severity_enum')),
                              nullable=False),
                    sa.Column('llm_provider', sa.Enum('AZURE_OPENAI', 'AWS_BEDROCK_CLAUDE', name='llm_provider_enum'),
                              nullable=True),
                    sa.Column('llm_connection_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
                    sa.Column('embedding_provider', sa.Enum('AZURE_OPENAI', name='embedding_provider_enum'),
                              nullable=True),
                    sa.Column('embedding_connection_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
                    sa.Column('mcp_connections', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
                    sa.Column('code_triaging_agent_enabled', sa.Boolean(), nullable=False),
                    sa.Column('code_triaging_agent_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
                    sa.Column('orchestrator_agents', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'),
                              nullable=False),
                    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'),
                              nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('runbooks',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('title', sa.String(length=255), nullable=False),
                    sa.Column('content', sa.Text(), nullable=False),
                    sa.Column('content_size_bytes', sa.Integer(), nullable=False),
                    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
                    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'),
                              nullable=False),
                    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'),
                              nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index('idx_runbooks_embedding_hnsw', 'runbooks', ['embedding'], unique=False, postgresql_using='hnsw',
                    postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_l2_ops'})
    op.create_table('evaluations',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('alert_id', sa.Integer(), nullable=False),
                    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'SUCCESS', 'ERROR', name='status_enum'),
                              nullable=True),
                    sa.Column('job_id', sa.String(length=255), nullable=True),
                    sa.Column('root_cause_score', sa.Float(), nullable=True),
                    sa.Column('agent_coordination_score', sa.Float(), nullable=True),
                    sa.Column('tool_utilization_score', sa.Float(), nullable=True),
                    sa.Column('task_completion_score', sa.Float(), nullable=True),
                    sa.Column('tokens_used', sa.Integer(), nullable=True),
                    sa.Column('price_usd', sa.Numeric(precision=10, scale=4), nullable=True),
                    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'),
                              nullable=False),
                    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'),
                              nullable=False),
                    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_evaluations_alert_id'), 'evaluations', ['alert_id'], unique=False)
    op.create_index(op.f('ix_evaluations_job_id'), 'evaluations', ['job_id'], unique=False)
    op.create_index(op.f('ix_evaluations_status'), 'evaluations', ['status'], unique=False)
    op.create_table('triages',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('alert_id', sa.Integer(), nullable=False),
                    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'SUCCESS', 'ERROR', name='status_enum'),
                              nullable=True),
                    sa.Column('thread_id', sa.String(length=255), nullable=True),
                    sa.Column('job_id', sa.String(length=255), nullable=True),
                    sa.Column('error_message', sa.Text(), nullable=True),
                    sa.Column('root_cause_summary', sa.Text(), nullable=True),
                    sa.Column('tokens_used', sa.Integer(), nullable=True),
                    sa.Column('price_usd', sa.Numeric(precision=10, scale=4), nullable=True),
                    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'),
                              nullable=False),
                    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'),
                              nullable=False),
                    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_triages_alert_id'), 'triages', ['alert_id'], unique=False)
    op.create_index(op.f('ix_triages_job_id'), 'triages', ['job_id'], unique=False)
    op.create_index(op.f('ix_triages_status'), 'triages', ['status'], unique=False)
    op.create_index(op.f('ix_triages_thread_id'), 'triages', ['thread_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_triages_thread_id'), table_name='triages')
    op.drop_index(op.f('ix_triages_status'), table_name='triages')
    op.drop_index(op.f('ix_triages_job_id'), table_name='triages')
    op.drop_index(op.f('ix_triages_alert_id'), table_name='triages')
    op.drop_table('triages')
    op.drop_index(op.f('ix_evaluations_status'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_job_id'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_alert_id'), table_name='evaluations')
    op.drop_table('evaluations')
    op.drop_index('idx_runbooks_embedding_hnsw', table_name='runbooks', postgresql_using='hnsw',
                  postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_l2_ops'})
    op.drop_table('runbooks')
    op.drop_table('app_config')
    op.drop_index(op.f('ix_alerts_external_id'), table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
