"""automatic triage enabled

Revision ID: ad359fb9d063
Revises: f3872377b49d
Create Date: 2025-10-31 08:31:12.149301

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ad359fb9d063'
down_revision: Union[str, Sequence[str], None] = 'f3872377b49d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_config', sa.Column('automatic_triage',
                                          sa.Boolean(), server_default='true', nullable=False))
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_column('app_config', 'automatic_triage')
    # ### end Alembic commands ###
