"""add_secondary_llm_support

Revision ID: bb2966c11979
Revises: 5a74b2c2453b
Create Date: 2025-09-29 22:30:52.637310

"""
import logging
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bb2966c11979'
down_revision: Union[str, Sequence[str], None] = '5a74b2c2453b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

logger = logging.getLogger(__name__)


def upgrade() -> None:
    """
    Add secondary LLM support with proper data migration.

    This migration:
    1. Renames existing LLM columns to primary_llm_*
    2. Adds secondary LLM configuration columns
    3. Migrates existing data and adds same_as_primary flag to secondary configs
    """

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_config', sa.Column('primary_llm_provider',
                                          sa.Enum('AZURE_OPENAI', 'AWS_BEDROCK_CLAUDE', name='llm_provider_enum'),
                                          nullable=True))
    op.add_column('app_config',
                  sa.Column('primary_llm_connection_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('app_config', sa.Column('secondary_llm_provider',
                                          sa.Enum('AZURE_OPENAI', 'AWS_BEDROCK_CLAUDE', name='llm_provider_enum'),
                                          nullable=True))
    op.add_column('app_config',
                  sa.Column('secondary_llm_connection_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('app_config', 'llm_connection_config')
    op.drop_column('app_config', 'llm_provider')
    # ### end Alembic commands ###

    # Data migration: Add same_as_primary flag to existing secondary LLM configurations
    connection = op.get_bind()

    update_query = """
                   UPDATE app_config
                   SET secondary_llm_connection_config = secondary_llm_connection_config || '{"same_as_primary": false}'::jsonb
                   WHERE secondary_llm_connection_config IS NOT NULL
                     AND secondary_llm_connection_config != 'null'::jsonb
                     AND NOT (secondary_llm_connection_config ? 'same_as_primary') \
                   """

    result = connection.execute(sa.text(update_query))
    if result.rowcount > 0:
        logger.info(f"Updated {result.rowcount} existing secondary LLM configs with same_as_primary=false")


def downgrade() -> None:
    """
    Remove secondary LLM support and revert to original schema.

    This downgrade:
    1. Removes same_as_primary flag from secondary LLM configurations
    2. Removes secondary LLM configuration columns
    3. Reverts primary_llm_* column names back to llm_*
    """

    # Data migration: Remove same_as_primary flag from secondary LLM configurations
    connection = op.get_bind()

    downgrade_query = """
                      UPDATE app_config
                      SET secondary_llm_connection_config = secondary_llm_connection_config - 'same_as_primary'
                      WHERE secondary_llm_connection_config IS NOT NULL
                        AND secondary_llm_connection_config != 'null'::jsonb
    AND (secondary_llm_connection_config ? 'same_as_primary') \
                      """

    result = connection.execute(sa.text(downgrade_query))
    if result.rowcount > 0:
        logger.info(f"Removed same_as_primary flag from {result.rowcount} secondary LLM configs")

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_config', sa.Column('llm_provider', postgresql.ENUM('AZURE_OPENAI', 'AWS_BEDROCK_CLAUDE',
                                                                          name='llm_provider_enum'),
                                          autoincrement=False, nullable=True))
    op.add_column('app_config',
                  sa.Column('llm_connection_config', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False,
                            nullable=True))
    op.drop_column('app_config', 'secondary_llm_connection_config')
    op.drop_column('app_config', 'secondary_llm_provider')
    op.drop_column('app_config', 'primary_llm_connection_config')
    op.drop_column('app_config', 'primary_llm_provider')
    # ### end Alembic commands ###
